# hugo.site.toml - Configurations for the site content
#
# ** DO NOT OVERRIDE ANY SETTING FROM hugo.toml. IT WILL NOT WORK **
#
# Also, do *not* introduce new variables here without a counterpart in
# hugo.toml, to avoid conflicts with future builds.
#
#   An exception to this rule is to add new values to maps, such as keys.
#
#   In other words, introducing a new [params.xxx] is a no-no, but
#   [params.yyy.zzz] whenever yyy exists is okay to add new zzz.

title = 'Union.ai Docs'

[params]
_merge = "deep"
signup_link = "https://www.union.ai/pricing"
docs_root = "https://www.union.ai/docs"

custom_css = [
  "404.css",
  "api.css",
  "base.css",
  "breadcrumb.css",
  "flyte-banner.css",
  "card.css",
  "chroma.css",
  "codeblock.css",
  "footer.css",
  "header.css",
  "heading.css",
  "images.css",
  "key.css",
  "markdown.css",
  "mermaid.css",
  "plugin.css",
  "search.css",
  "sidebar.css",
  "tabs.css",
  "toc.css",
]
custom_js = [
  "404.js",
  "key.js",
  "sidebar.js",
  "theme.js",
  "tags.js",
  "inline-code-linker.js",
  "codeblock-linker.js",
  "codeblock-copy-strip.js",
]

[params.variant_weights]
flyte = 1
byoc = 2
selfmanaged = 3


#----------------------------------------------------------
# Keywords

#
# Used by {{< key >}} shortcode. See:
# https://www.union.ai/docs/v2/flyte/community/contributing-docs/variants/#key
#
# ===== IMPORTANT =====
#
# DO NOT add new keys here without, in the same PR, adding them to the
# documentation above as well.
#
[params.key]

[params.key.default_project]
flyte = "flytesnacks"
byoc = "flytesnacks"
selfmanaged = "flytesnacks"

[params.key.product_full_name]
flyte = "Flyte OSS"
byoc = "Union.ai BYOC"
selfmanaged = "Union.ai Self-managed"

[params.key.product_name]
flyte = "Flyte"
byoc = "Union.ai"
selfmanaged = "Union.ai"

[params.key.product]
flyte = "flyte"
byoc = "union"
selfmanaged = "union"

[params.key.kit_name]
flyte = "Flytekit"
byoc = "Union"
selfmanaged = "Union"

[params.key.kit]
flyte = "flytekit"
byoc = "union"
selfmanaged = "union"

[params.key.kit_as]
flyte = "fl"
byoc = "union"
selfmanaged = "union"

[params.key.kit_import]
flyte = "flytekit as fl"
byoc = "union"
selfmanaged = "union"

[params.key.kit_remote]
flyte = "FlyteRemote"
byoc = "UnionRemote"
selfmanaged = "UnionRemote"

[params.key.cli_name]
flyte = "Pyflyte"
byoc = "Union"
selfmanaged = "Union"

[params.key.cli]
flyte = "pyflyte"
byoc = "union"
selfmanaged = "union"

[params.key.ctl_name]
flyte = "Flytectl"
byoc = "Uctl"
selfmanaged = "Uctl"

[params.key.ctl]
flyte = "flytectl"
byoc = "uctl"
selfmanaged = "uctl"

[params.key.config_env]
flyte = "FLYTECTL_CONFIG"
byoc = "UNION_CONFIG"
selfmanaged = "UNION_CONFIG"

[params.key.env_prefix]
flyte = "FLYTE"
byoc = "UNION"
selfmanaged = "UNION"

[params.key.docs_home]
flyte = "https://www.union.ai/docs/flyte"
byoc = "https://www.union.ai/docs/byoc"
selfmanaged = "https://www.union.ai/docs/selfmanaged"

[params.key.map_func]
flyte = "map_task"
byoc = "map"
selfmanaged = "map"

[params.key.logo]
flyte = "icon-logo-flyte.png"
byoc = "icon-logo.svg"
selfmanaged = "icon-logo.svg"

[params.key.favicon]
flyte = "icon-logo-flyte.png"
byoc = "favicon.ico"
selfmanaged = "favicon.ico"

# Please DO NOT add new keys without documenting them the contributing guide in the same PR.
