#!/usr/bin/env python3

import argparse

import yaml

from lib.parser.parse import parse


def main():
    parser = argparse.ArgumentParser(
        description="Generate API documentation from Python package"
    )
    parser.add_argument("--package", help="Package to parse", required=True)
    parser.add_argument("--output", help="Output file", required=True)
    parser.add_argument(
        "--all-only",
        action="store_true",
        help="Only parse symbols in __all__, skip subpackage discovery",
    )
    args = parser.parse_args()

    result = parse(args.package, all_only=args.all_only)

    yaml_output = yaml.dump(
        result,
        sort_keys=True,
        default_flow_style=False,
    )

    with open(args.output, "w") as f:
        f.write(yaml_output)


if __name__ == "__main__":
    main()
