#!/bin/bash
# check-asset-refs.sh — every CSS/JS URL in the built site resolves to a real file.
#
# Why this exists (DOC-1316). Content-hashed asset URLs are generated by Hugo, so
# they are right by construction — but only for assets Hugo emits. Anything
# referenced from outside the Hugo build is not covered, and that is exactly where
# the bugs were: index.html.tmpl is substituted by sed in the Makefile, and it had
# been pointing at /docs/v2/css/home.css for as long as the file existed. Static
# assets publish PER VARIANT, so the real path is /docs/v2/<variant>/css/. It 404'd
# in production the whole time, masked by the Cloudflare redirect that shadows
# /docs/.
#
# Nothing in CI was checking this. "Check Internal Links" walks page links, not
# asset references.
#
# NOTE the regex accepts a trailing query string. The first version of this check
# required the ref to end at the extension, so it skipped `home.css?v=...` entirely
# and reported a confident 0-missing while that file was broken. A check that
# cannot see the failing case is worse than no check.
#
# Usage: scripts/check-asset-refs.sh [dist-dir]
set -uo pipefail
DIST="${1:-dist}"
missing=0; checked=0; declare -a bad=()
while IFS= read -r page; do
  while IFS= read -r ref; do
    [ -z "$ref" ] && continue
    checked=$((checked+1))
    path="${ref%%\?*}"                 # strip any ?v=
    [ -f "$DIST$path" ] || { bad+=("$ref  <- $page"); missing=$((missing+1)); }
  done < <(grep -ohE '(href|src)="(/[^"]*\.(css|js)(\?[^"]*)?)"' "$page" | sed 's/.*="//;s/"$//')
done < <(find "$DIST" -name '*.html')
echo "checked $checked references, $missing missing"
if [ $missing -gt 0 ]; then printf '  %s\n' "${bad[@]}" | sort -u | head -20; exit 1; fi
